name: "unit test"

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [4, 6, 8, 10, 12, 14]
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Checkout PR branch
        uses: actions/checkout@v1
      - run: npm install
      - run: npm test
